### ISSUE TITLE
docker-compose does not work in windows

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes-editor-ui#7]
A/C:
- guide in README is created for both --  users that uses Powershell and users that use WSL
- it is tested
- either show how to use './bin/spe.sh' on windows to open editor in specified folder from commandline, or create own './bin/spe.bat' file

**Comment by blcham** [comment]
@rodionnv please describe here

**Comment by rodionnv** [comment]
Docker-compose can't load scripts from `/mnt/c/.../s-pipes-modules` and `/mnt/c/.../s-pipes/doc/examples`. In the logs NoSuchFileException can be seen.
But, after I have tried to create examples folder directly in linux so the path was /home/.../s-pipes/doc/examples, it was able to read it, and after this, it is now able to load scripts from /mnt/c/.../doc/examples. I don't really know what's the reason because i haven't changed anything apart from trying to load scripts from different places.

**Comment by blcham** [comment]
So please put here what did you have to change in configuration so it works. I guess there are some changes in docker compose file right (volume mapping of /mnt ?)

**Comment by rodionnv** [comment]
Yes, i have added volumes /mnt:/mnt in docker-compose.yml both in s-pipes-editor-rest and s-pipes-engine sections

**Comment by blcham** [comment]
@kostobog
